### ISSUE TITLE
App does not start after update to 0.22.0

### ISSUE THREAD

**Issue by The-Nickname** [lneugebauer/nextcloud-cookbook#107]
**Describe the bug**

**To Reproduce**
1. Useing version 0.21.1 via F-Droid on Android 10
2. Update to version 0.22.0
3. Attempt to start the App
4. App doesn't launch, after multiple attempts I get the default Android message "App got shut down repetitively"

**Expected behavior**
 App should start and work normal.

**Smartphone:**

 - Device: Shift 6mq
 - OS: Android 10
 - Version: 3.10 L

**Comment by lneugebauer** [comment]
@The-Nickname this issue is already resolved. It will take F-Droid a couple oft days to build and deploy.

If you don't want to wait, you can download the latest release from GitHub.
