### ISSUE TITLE
Sharing recipes

### ISSUE THREAD

**Issue by Markoise** [lneugebauer/nextcloud-cookbook#112]
**Is your feature request related to a problem? Please describe.**
When you share a recipe, the text is copied to the clipboard on your smartphone. You then share a huge text. This is good if you share a recipe with people who don't have access to the Nextcloud server.

**Describe the solution you'd like**
It should also be possible to share the recipe in such a way that recipients are automatically taken to the recipe within the app.

**Comment by lneugebauer** [comment]
Hi @Markoise, thanks for the suggestion. As there isn't an official way to share recipes with other users, I won't implement such a feature.

In the near future, my app will support deep links which kind of fulfills your request. However, this will only work if you log in with the same account or share the recipe folder, as mentioned in the docs.

So in the future, when you click a link like `lneugebauer.github.io/recipe/<RECIPE_ID>`, the app will open.

https://nextcloud.github.io/cookbook/user/#sharing-with-another-nextcloud-user
https://lneugebauer.github.io/nextcloud-cookbook/faqs.html#how-can-i-share-recipes

**Comment by Markoise** [comment]
Wonderful. That's exactly what I meant.
I look forward to the update one day
