### ISSUE TITLE
Recipe Order A-Z and Date added/edited (reversed)

### ISSUE THREAD

**Issue by xmgz** [lneugebauer/nextcloud-cookbook#117]
**Is your feature request related to a problem? Please describe.**

Recipes are ordered A-Z but most of the time user has more interest in **recently added recipes** that, because of its name, may be way down in the list or even does not remember what **title** they wrote. 

**Describe the solution you'd like**

it's a suggestion

**Describe alternatives you've considered**

none

**Additional context**

screen shot of recipe's tab. Up there you can put a control to «sort» by date/name and reverse or a drop down menu (what best follows desing principles)

![Screenshot_20241119-141626_Receitas_de_coci�a_1_1](https://github.com/user-attachments/assets/1fcfe4b3-e30c-47ec-96cc-a6b8f34bdad2)

thank you

**Comment by lneugebauer** [comment]
Thats a great suggestion! I'll implement that in the future.
