### ISSUE TITLE
«Issues» section title is not translatable

### ISSUE THREAD

**Issue by xmgz** [lneugebauer/nextcloud-cookbook#118]
**Describe the bug**

«Issues» is a *read-only* text chain
 https://hosted.weblate.org/translate/nextcloud-cookbook/app/gl/?checksum=a745f9066a463bd7

**To Reproduce**
1. Go to Settings and scroll down (or  link above)

**Expected behavior**

use the term in the same language as UI

**Screenshots**

![Screenshot_20241119-141544_Receitas_de_cocia_1_1](https://github.com/user-attachments/assets/a25551c7-7bef-4259-bbf3-6eb1357f2147)

**Additional context**

…in case you missed it.

thank you

**Comment by lneugebauer** [comment]
I think I intentionally marked that string as read-only to have a connection to GitHubs issues. Especially for less techy people, that may wonder what they are supposed to do on GitHub, if they don't know about issues and code collaboration in general.

Not sure if that's a good decision. I'm open for suggestions.

**Comment by xmgz** [comment]
yes, I think understand your point of view :+1: 

I would add that just below this title there's a short description that describes what is about. So maybe something like «Get involved», «Contribute», «Your voice»(!), … I'm not sure about any of these or others are better than **Issues**, but user has that short description to get an idea about what to expect. I'm not even sure you *should* change it :smile: 

thank you.
