### ISSUE TITLE
Add search and filter

### ISSUE THREAD

**Issue by Slomo17** [lneugebauer/nextcloud-cookbook#18]
I would love to see a search function and the ability to filter for keywords. E.g. if i want to eat something with potatoes in can filter for this keyword and see all recipes with the keyword potatoe.

**Comment by xdubx** [comment]
UX proposal:

Add Button open up dropdown to the top and select the search button or add button.

Screenshot follows.

**Comment by Slomo17** [comment]
Seems good to me. This way the UI will not be cluttered too much.
