### ISSUE TITLE
Fails to open certain recipes

### ISSUE THREAD

**Issue by TheSunCat** [lneugebauer/nextcloud-cookbook#19]
I have imported [this](https://prettysimplesweet.com/black-forest-cake/) recipe URL using this app, and it shows up fine in the Nextcloud Cookbook web UI, but fails to open in the Android app. The recipe thumbnail is shown correctly, but when tapped, the text `Exception: type '_OneByteString' is not a subtype of type 'int'` is shown. The edit button at the top right does nothing.

**Comment by lneugebauer** [comment]
Hey @TheSunCat, sadly I couldn't reproduce your issue. I imported the recipe using the web apps "import by url" functionality. After opening this Android app I was able to open, edit and save the recipe just fine.
