### ISSUE TITLE
Add deployment for f-droid

### ISSUE THREAD

**Issue by xdubx** [lneugebauer/nextcloud-cookbook#21]
Docs: https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/

**Comment by IzzySoft** [comment]
Or simply provide a signed release-APK attached to its corresponding release and I could pick it up for [my repo](https://apt.izzysoft.de/fdroid) :wink:

**Comment by IzzySoft** [comment]
No chance, @lneugebauer? There's a "Get it on Github" badge in the Readme pointing to releases, but whoever follows it will be quite disappointed at the moment.

**Comment by lneugebauer** [comment]
Hey @IzzySoft, I'm still reading up on this topic and have scheduled it for mid-June. I'm not sure yet if I'll try to release it through the official F-Droid repository or use some kind of mirror - as you suggested.

**Comment by IzzySoft** [comment]
Thanks for the update and clarification Lukas! I saw you've self-assigned it, but without any note the process was not clear. Now it is :smiley:

**Comment by lneugebauer** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13368

**Comment by lneugebauer** [comment]
Merge Request got accepted! 🥳
