### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ceskyDJ** [lneugebauer/nextcloud-cookbook#24]
**Is your feature request related to a problem? Please describe.**
Some users don't speak English at all, so your application is useless for them.

**Describe the solution you'd like**
I'd like to see support for community translations in your application, so more users could use it and completely understand it.

**Comment by lneugebauer** [comment]
Hey @ceskyDJ, you are able to add translations via Android Studio. I'll update the README in the following days to better describe this process.

**Comment by ceskyDJ** [comment]
That's nice. Where can I change app language after? I don't see it anywhere (even in global Android setting for application).

**Comment by lneugebauer** [comment]
The language depends on your device settings. If you have set your device language to German it will show German strings. As there are only English and German strings available currently it will fall back to English strings for all other languages.

**Comment by ceskyDJ** [comment]
Ah, thanks!
