### ISSUE TITLE
Bad behavior when no categories available

### ISSUE THREAD

**Issue by ceskyDJ** [lneugebauer/nextcloud-cookbook#26]
**Describe the bug**
I added some recipes without category and "Categories" screen doesn't work properly.

**To Reproduce**
1. Open app
2. Log in with new account with no recipes
3. Add one or more recipes without category
4. Go to screen "Categories"
5. See "*" category (as shown in screenshot below)

**Expected behavior**
As no categories are defined, show message "No categories found".

**Screenshots**
![Screenshot_20230517_170013_Cookbook](https://github.com/lneugebauer/nextcloud-cookbook/assets/48548230/edc4aa44-217d-4eb4-976f-15da73d01aa8)

**Smartphone:**
 - Device: Samsung Galaxy S22
 - OS: Android 13
 - Version: 0.8.0 (14)

**Comment by lneugebauer** [comment]
Hey @ceskyDJ, this is actually the default behaviour of the [cookbook API](https://nextcloud.github.io/cookbook/dev/api/0.1.0/index.html#/Categories/get_api_v1_categories). Take a look at the `GET /api/v1/categories` response. All recipes that don't have a category associated with them will be put into a `*` category

**Comment by ceskyDJ** [comment]
Interesting. So, what about to process it like web version of Nextcloud does – shows that recipies as "Uncategorized recipes"? I think the "star" is just a internal special value, so end users should see something better. But it's only my point of view, it's up to you, of course.
