### ISSUE TITLE
Filter recipes by tag

### ISSUE THREAD

**Issue by Markoise** [lneugebauer/nextcloud-cookbook#30]
It would be very useful if you could filter the recipes by tag.  In my opinion, the category alone is not enough if you have a large collection.

**Comment by lneugebauer** [comment]
Hej @Markoise, thank you for your suggestion. I already thought about implementing something like this and will do so in the future.

I'll probably do this in three steps:

1. [ ] Add tags to the create and edit screen of recipes.
2. [ ] Make tags clickable and show all recipes with the same tag. (Similar to the categories screen.)
3. [ ] Implement the [search API endpoint](https://nextcloud.github.io/cookbook/dev/api/0.1.1/index.html#/Recipes/search) so you are able to search for categories, tags and recipe names.
