### ISSUE TITLE
APK availability

### ISSUE THREAD

**Issue by IzzySoft** [lneugebauer/nextcloud-cookbook#33]
Your Readme shows a badge stating one could get the app from Github releases – but there aren't any APKs attached to the releases. Did you just forget to attach them, or is it some Github workflow failing?

**Comment by lneugebauer** [comment]
Hej @IzzySoft, there is currently no process for creating GitHub releases. I'll be working on this while also making the APK available on F-Droid (#21).

**Comment by IzzySoft** [comment]
Ah, yes, I vaguely remembered there was something (but mid-June has passed :see_no_evil:). Still, that badge is a bit misleading then :wink: If there were an APK available there (e.g. attached manually), I probably could list your app in my repo, picking the APK from there, until you're ready for F-Droid.org …

**Comment by lneugebauer** [comment]
Well, I meant July. Definitely scheduled it for this weekend in my calendar… Anyways, I'm working on it.

June, July – we really should have different names for these.

**Comment by IzzySoft** [comment]
Thanks! Looking forward to your next ping then :smiley:
