### ISSUE TITLE
Play protect blocks installation via APK file from GitHub

### ISSUE THREAD

**Issue by ceskyDJ** [lneugebauer/nextcloud-cookbook#37]
**Describe the bug**
When I try to install this app via APK file downloaded from GitHub release, Play protect blocks it (see attached screenshot). There is a way, how to workaround this by showing more details (screenshot contains this screen) and tapping on "Install anyway".

**To Reproduce**
1. Download APK file from GitHub release
2. Try to install app via downloaded APK file
3. See alert from Play protect (as displayed on screenshot below)

**Expected behavior**
App is installed without blocking and alert from Play protect.

**Screenshots**
![Screenshot_20230813_172044_Google Play Store](https://github.com/lneugebauer/nextcloud-cookbook/assets/48548230/634975df-eb67-4a76-abc0-e4839fa6752a)

**Smartphone:**
 - Device: Samsung Galaxy S22
 - OS: Android 13
 - Version 0.12.0+26

**Comment by ceskyDJ** [comment]
After installation Play protect showed another alert about sending app to Google for safety checking. So, I let it send to Google and maybe they add your signature to known ones or something like that. I completely don't know how these things around mobile apps works, so it could be just a mistake on your side, so I created this issue for this case.

**Comment by lneugebauer** [comment]
Hi @ceskyDJ, as the GitHub release is signed by me, unlike the Google Play Store release, which is signed by Google, this warning appears. I'll try to get the GitHub release approved as well, so this warning will not appear in the future.

**Comment by ceskyDJ** [comment]
Thanks for your explanation!

**Comment by lneugebauer** [comment]
@ceskyDJ can you please try again?

**Comment by ceskyDJ** [comment]
It works like a charm! Thanks ❤️.

**Comment by ceskyDJ** [comment]
I tried to install a new version (0.12.1+27) via Obtainium (so internally just via APK from GitHub release) and it didn't work again with the same error. See:
![Screenshot_20230814_200817_Google Play Store](https://github.com/lneugebauer/nextcloud-cookbook/assets/48548230/ec17ef08-150e-402f-bfb3-d8092bdbdf5d)

**Comment by ceskyDJ** [comment]
> It works like a charm! Thanks heart.

This result was done by:
1. Uninstall app (version v0.12.0+26)
2. Install app using Obtainium again (via APK from GitHub release for version v0.12.0+26)

**Comment by ceskyDJ** [comment]
Ok, thanks.
