### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by newhinton** [lneugebauer/nextcloud-cookbook#46]
Hi! While browsing the nextcloud cookbook developer documentation, i found out that you have created a new android app. So far it looks good, but glancing from the featureset, it looks like we are trying to solve the same issue. (I am not the maintainer of the micmun-cookbook-app, just helping out regulary)

Since we are trying to solve the same issue, maybe it would be possible to join forces in some way? (As an example, i am currently hard at work implementing editing). I am not really close in touch with the other maintainer, but we could try to make it more active!

Sorry if i am intruding unwelcome. Otherwise, thanks!

**Comment by lneugebauer** [comment]
Hi @newhinton, as my free time is quite limited, I probably won't be able to contribute any code to the micmun-cookbook-app. If you have any concrete plans on how we can join forces or support each other, I'd be happy to hear from you. We'll see if we can make something happen.

**Comment by lneugebauer** [comment]
Hi @newhinton, I'll close the issue for now. If you have any questions or proposals feel free to reopen this issue, create a new one or contact me via mail.
