### ISSUE TITLE
share recipies with others via external link

### ISSUE THREAD

**Issue by foss-** [lneugebauer/nextcloud-cookbook#61]
It would be a nice feature, if users could share their recipies with users by sharing an external link. Ideally that would be an external link (analogue to external links when sharing files) allowing to share links also with people that are not users on the nextcloud instance.

**Comment by lneugebauer** [comment]
Hi @foss-, thank you for your suggestion. As far as I know, there is no possibility to share the recipe with another Nextcloud instance by an external link. I'd suggest to take a look at the [Nextcloud Cookbook repository](https://github.com/nextcloud/cookbook). You may already find a feature request over there. If I'm simply unaware of this feature, please correct me.

**Comment by lneugebauer** [comment]
The reason I don't want to implement this is that if the Nextcloud app doesn't provide this feature, I would have to send this data over my own server, and I'd like to avoid that.
