### ISSUE TITLE
Feature Request: Nutrition Information

### ISSUE THREAD

**Issue by Saijin-Naib** [lneugebauer/nextcloud-cookbook#64]
**Is your feature request related to a problem? Please describe.**
Many recipes have nutrition information available for a given serving size. 

**Describe the solution you'd like**
It would be amazing if we could input things like macro and micro nutrient info alongside calories. 

**Describe alternatives you've considered**
Using description sort of works, but it is static and cant be filtered or grouped on. 

**Additional context**
Having this scale along with serving size would be phenomenal.

**Comment by lneugebauer** [comment]
@Saijin-Naib great catch! As I don't use nutritional information in my recipes, I completely forgot about it. I'll add it in a future version!
