### ISSUE TITLE
Feature Request: GroupFolder or other Sharing Support

### ISSUE THREAD

**Issue by Saijin-Naib** [lneugebauer/nextcloud-cookbook#65]
**Is your feature request related to a problem? Please describe.**
I can not currently share creation and maintenance of recipes with my family on our NextCloud. 

**Describe the solution you'd like**
Being able to use the GroupFolder or otherwise to share our recipe inventory would be amazing. 

**Describe alternatives you've considered**
Currently, I input everything and my wife borrows my phone to use the app. 

**Additional context**
As it stands, phenomenal for regular individual usage. Just a bit clunky for family usage.

**Comment by lneugebauer** [comment]
Hi @Saijin-Naib, I'm afraid there's not much I can do to improve the sharing/syncing of recipes with other Nextcloud users. This is functionality that the cookbook plugin has to provide, as I'm only using the API that the plugin provides. #61 is a similar feature request, there are some related issues that may be of interest to you.

To share recipes with my wife, I simply use the same Nextcloud account on both phones. Obviously this doesn't allow sharing via the browser, but it works for us as she only uses the app.
