### ISSUE TITLE
Feature Request: Numeric Quantities per Ingredient Line Item

### ISSUE THREAD

**Issue by Saijin-Naib** [lneugebauer/nextcloud-cookbook#66]
**Is your feature request related to a problem? Please describe.**
Quantity is currently the same string as the ingredient. Does it go first, last? How do we separate it? It can not scale with servings. 

**Describe the solution you'd like**
Being able to input the numeric quantity and unit alongside the ingredient string. 

**Describe alternatives you've considered**
Using as-is, but I am already seeing I am not self-consistent, let alone with other family users inputting stuff. 

**Additional context**
Will likely be necessary for serving size scaling.

**Comment by lneugebauer** [comment]
Hi @Saijin-Naib, thank you for your suggestion. Please take a look at the web app, how they handle quantities. Iirc the quantity should go first, separated by a space.

As mentioned in #62, I'll work on implementing the same behaviour in my app in the future. I'm closing this in favour of before mentioned issue.
