### ISSUE TITLE
Shopping list

### ISSUE THREAD

**Issue by lneugebauer** [lneugebauer/nextcloud-cookbook#7]
Add the possibility to add the ingredients of a recipe to some shopping list.

As a first version this could be a local shopping list. E.g. stored in room.

For later updates ingredients could be stored in multiple other apps.

**Comment by Slomo17** [comment]
I would like if this could be implemented using the already present sharing function. Instead of sharing the whole recipe only share the incredients (maybe with markdown checkboxes), so it can be shared to any other note app using the android sharing system e.g. the nextcloud notes app.

**Comment by lneugebauer** [comment]
@Slomo17 that sounds like a great idea. I'll probably add this in the future as I don't really want to add a full shopping list to this app anymore. It doesn't feel like the right place to store that information.
