### ISSUE TITLE
[Contribution] [Weblate] New language, galician (gl)

### ISSUE THREAD

**Issue by xmgz** [lneugebauer/nextcloud-cookbook#80]
Hi, many **thanks** for your app.

I have translate it to my language (galician, language code: `gl`, `gl_ES`) in weblate.

I hope you can added. Thank you.

(opened this as a *Feature Request*, as it is not an *issue* or problem :hugs: )

**Comment by lneugebauer** [comment]
Thank you for contributing! Weblate will automatically create a pull request for me to accept. :)
