### ISSUE TITLE
Serving adjustments don't work with fractions

### ISSUE THREAD

**Issue by Vortex-TH** [lneugebauer/nextcloud-cookbook#84]
I have a recipe that uses fractions
![screen1](https://github.com/user-attachments/assets/3567db0d-cc91-4ede-9698-dcfe9e26c080)

However they are not affected by changing the number of servings

![screen2](https://github.com/user-attachments/assets/f8525bc0-051c-47df-a855-59a6f6c3a16d)

I think it should also work with fractions.

App version **v0.18.0+40**

**Comment by lneugebauer** [comment]
Hey @Vortex-TH, you're using special characters as fractions. If you use regular characters, e.g. 1/2 instead of ½, fractions are already supported. This should be the same behaviour as in the web app.

**Comment by Vortex-TH** [comment]
You're right, but I think it would be good to support these special characters as well (since they were imported like this from a recipe website). Or at least convert them to another format automatically.
