### ISSUE TITLE
Copy ingredients for shopping list

### ISSUE THREAD

**Issue by feinmann** [lneugebauer/nextcloud-cookbook#86]
**Is your feature request related to a problem? Please describe.**
When I cook a certain recipe, I go through the ingredients. And when one is missing in my household, I want to write down the ingredient on my shopping list (that is a simple txt note).

**Describe the solution you'd like**
It would be great if I could copy all ingredients with one tap. And also single ingredients with one tap. Maybe it could also make sense to mark the ingredients by availability, and then copy the unavailable ones with one tap.

**Describe alternatives you've considered**
Alternative so far is writing down manually, which works. But sometimes you have also measures, and then it gets sometimes difficult. Other alternative is to go into edit mode, mark the ingredient and copy through context menu after long tap.

**Comment by lneugebauer** [comment]
Hi @feinmann, thank you for your feature request.

I've already added a button to copy all ingredients to the clipboard. That feature will be shipped with the next release!

Inspired by your request, I'll also added the option to copy ingredients one by one by long pressing the desired ingredient in the future.
