### ISSUE TITLE
is ⋮ a menu item?

### ISSUE THREAD

**Issue by xmgz** [lneugebauer/nextcloud-cookbook#96]
**Describe the bug**

I don't know if this is a bug or not

in Home screen every recipe has a three dot indicator (⋮) on the right side, but clicking on it does not open any menu as intuitively one would expect for such UI element.

**To Reproduce**
1. Go to Home
2. Click on ⋮ element in any recipe
3. nothing happens

**Expected behavior**

some kind of  menu (open, share, export, print, whatever)

**Screenshots**
![Screenshot_20240915-064236_Cookbook_1](https://github.com/user-attachments/assets/0740b3a8-2d02-40ea-9d31-47dee002ea35)

## Smartphone:

this could be important as **it's pretty old android device** (that works fine btw)

 - OS: android 9
 - Version, /e/ (lineageOS fork)
 - cookbook app 0.21.0
 - cookbook nextcloud (latest released version too)

**Additional context**

I can test in Android 12 device in a few days if you want, but please I wanted to know if this element has any function? thank you

**Comment by lneugebauer** [comment]
Hi @xmgz, thank you for reporting this.

There is nothing wrong with your phone. Back when I started this project, I wanted to add a menu with some actions like sharing. Just as you mentioned.
I don't think that it fits the UI all that well as there isn't much space available. So I'll remove the 3 dot icon.
If I need to add some secondary action in the future, I'll use a long press.
